### ISSUE TITLE
[1.14.4] Weird crash with JEI

### ISSUE THREAD

**Issue by clonetrooper277** [MC-U-Team/Usefull-Backpacks-1.10.x#17] opened 2019-08-16 07:16 UTC
Crash log:
https://pastebin.com/41wK8wHj
produced by just opening my inventory.
I just recently updated to Forge 28.0.49 on 1.14.4 if that's any help.

**Comment by HyCraftHD** [comment] 2019-08-16 07:19
Thanks for the report. I'll have a lookt at it soon!

**Comment by clonetrooper277** [comment] 2019-08-16 07:19
That was fast!

**Comment by clonetrooper277** [comment] 2019-08-16 07:20
Should I report it  to the JEI developer?

**Comment by HyCraftHD** [comment] 2019-08-16 07:25
Yep. Seems like an issue with jei.

**Comment by clonetrooper277** [comment] 2019-08-16 07:25
Alright. Reporting it now!

**Comment by HyCraftHD** [comment] 2019-08-16 07:26
One question. How can you reproduce it? Or did it just crash randomly?

**Comment by HyCraftHD** [comment] 2019-08-16 07:31
Seems like this method was made private and jei tries to call it:
Class: net.minecraft.client.renderer.ItemRenderer
``` java
   private void renderModel(IBakedModel model, ItemStack stack) {
      this.renderModel(model, -1, stack);
   }
```

**Comment by clonetrooper277** [comment] 2019-08-16 07:33
I can reproduce by just opening my inventory. The two mods were working perfectly before I updated Forge. Maybe that's the issue?

**Comment by HyCraftHD** [comment] 2019-08-16 07:34
Well thats weird. Because I have no issues doing all this stuff with these versions.

**Comment by HyCraftHD** [comment] 2019-08-16 07:35
Seems still be an issue on jei's side so I cannot do much about it :/
https://github.com/mezz/JustEnoughItems/issues/1680

**Comment by clonetrooper277** [comment] 2019-08-16 07:37
Well, I'll just wait for mezz to fix it then.

**Comment by HyCraftHD** [comment] 2019-09-01 09:48
Fixed in jei, so I close this issue here

**Closed as completed by HyCraftHD** 2019-09-01 09:48 UTC
Labels: bug
